#!/bin/sh
# Kopiert $1 -> $2, falls die beiden Dateien nicht identisch sind

if [ -r $2 ]
then
	if cmp $1 $2 > /dev/null
	then
		echo "$2 ist noch aktuell"
	else
		echo "Bringe $2 auf aktuellen Stand"
		cp $1 $2
	fi
else
	cp $1 $2
fi
