# $Id$
# Leeres Makefile: vor dem Aufruf von ./configure geht nichts

all:	include/sysdep.h

include/sysdep.h:
	@chmod a+rx ./configure
	@sh ./configure --with-user=news --with-group=uucp \
		--with-files=/usr/local/libexec/uconnect

