# Makefile für das sendmail-Subverzeichnis

include ../../Makefile.global

all: zbatchsmtp

install:

clean:

clobber:
	-rm -f zbatchsmtp

tidy:

distrib:

zbatchsmtp: zbatchsmtp.in
	../../helpers/subst < zbatchsmtp.in > zbatchsmtp
