# Makefile für das inn-Subverzeichnis

include ../../Makefile.global

all: send-zcon

install:

clean:

clobber:
	-rm -f send-zcon

tidy:

distrib:

send-zcon: send-zcon.in
	../../helpers/subst < send-zcon.in > send-zcon
